workflows:
  android-release:
    name: Android Release Build

    environment:
      groups:
        - keystore_credentials   # This is your group name (keystore, passwords)

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Decode keystore
        script: |
          echo $KEYSTORE_BASE64 | base64 --decode > android/app/keystore.jks

      - name: Build Release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - kumarisurbhi.ctps@gmail.com
