workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1

    environment:
      # This section tells Codemagic to inject the file you uploaded to the UI
      android_signing:
        - my_release_keystore  # <--- MAKE SURE THIS MATCHES THE NAME IN UI

      vars:
        API_KEY: Encrypted(API_KEY)
        SUPABASE_URL: Encrypted(SUPABASE_URL)
        SUPABASE_ANON_KEY: Encrypted(SUPABASE_ANON_KEY)
        ASSEMBLYAI_API_KEY: Encrypted(ASSEMBLYAI_API_KEY)
        # Note: No KEYSTORE_BASE64 variable needed here anymore

    scripts:
      - name: Create .env file
        script: |
          echo "API_KEY=$API_KEY" >> .env
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "ASSEMBLYAI_API_KEY=$ASSEMBLYAI_API_KEY" >> .env

      - name: Install Flutter dependencies
        script: |
          flutter pub get

      # NOTICE: The "Decode keystore" script is GONE. Do not put it back.

      - name: Build Release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - kumarisurbhi.ctps@gmail.com