// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHlbqCldr3zJvRljWIzcUgJ-UdpnHZ98',
    appId: '1:145460828614:web:5688375c2cc3daa86a3ac7',
    messagingSenderId: '145460828614',
    projectId: 'notes-69d97',
    authDomain: 'notes-69d97.firebaseapp.com',
    storageBucket: 'notes-69d97.firebasestorage.app',
    measurementId: 'G-C8R1GJLG6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGoCs6hTF237Y5mfYvorO2iFrMpXMYZC0',
    appId: '1:145460828614:android:3473c3b8052aef506a3ac7',
    messagingSenderId: '145460828614',
    projectId: 'notes-69d97',
    storageBucket: 'notes-69d97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh9Yh16vbVir6WVu25d8cIuefwGpDPQig',
    appId: '1:145460828614:ios:78d5acb633954a786a3ac7',
    messagingSenderId: '145460828614',
    projectId: 'notes-69d97',
    storageBucket: 'notes-69d97.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh9Yh16vbVir6WVu25d8cIuefwGpDPQig',
    appId: '1:145460828614:ios:78d5acb633954a786a3ac7',
    messagingSenderId: '145460828614',
    projectId: 'notes-69d97',
    storageBucket: 'notes-69d97.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbHlbqCldr3zJvRljWIzcUgJ-UdpnHZ98',
    appId: '1:145460828614:web:1c02856bd39d96ce6a3ac7',
    messagingSenderId: '145460828614',
    projectId: 'notes-69d97',
    authDomain: 'notes-69d97.firebaseapp.com',
    storageBucket: 'notes-69d97.firebasestorage.app',
    measurementId: 'G-89BVTNP9ZX',
  );
}
